/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ViewRouteImport } from './routes/view'
import { Route as EditRouteImport } from './routes/edit'

const ViewRoute = ViewRouteImport.update({
  id: '/view',
  path: '/view',
  getParentRoute: () => rootRouteImport,
} as any)
const EditRoute = EditRouteImport.update({
  id: '/edit',
  path: '/edit',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/edit': typeof EditRoute
  '/view': typeof ViewRoute
}
export interface FileRoutesByTo {
  '/edit': typeof EditRoute
  '/view': typeof ViewRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/edit': typeof EditRoute
  '/view': typeof ViewRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/edit' | '/view'
  fileRoutesByTo: FileRoutesByTo
  to: '/edit' | '/view'
  id: '__root__' | '/edit' | '/view'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  EditRoute: typeof EditRoute
  ViewRoute: typeof ViewRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/view': {
      id: '/view'
      path: '/view'
      fullPath: '/view'
      preLoaderRoute: typeof ViewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/edit': {
      id: '/edit'
      path: '/edit'
      fullPath: '/edit'
      preLoaderRoute: typeof EditRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  EditRoute: EditRoute,
  ViewRoute: ViewRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
